version: "3.9"

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
    container_name: tinvest-analytics-frontend-node
    working_dir: /usr/src/app
    command: npm run build
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./webpack.config.js:/usr/src/app/webpack.config.js
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    env_file:
      - .env

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx
    container_name: tinvest-analytics-frontend-nginx
    depends_on:
      - node
    ports:
      - "8081:80"
#    volumes:
#      - ./dist:/usr/share/nginx/html
    env_file:
      - .env
